version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages # Install and automatically cache packages
      # Run optional required steps before releasing
      # - run: npm run build-script
      - run: npx semantic-release --dry-run

workflows:
  release-workflow:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - release
